# Generated by Django 3.0.3 on 2020-08-25 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Pizza', 'Pizza'), ('Topping', 'Topping'), ('Sub', 'Sub menu'), ('Extra', 'Extra'), ('Pasta', 'Pasta'), ('Salad', 'Salad'), ('Dinner Platter', 'Dinner Platter')], max_length=16)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('small_price', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('large_price', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Item')),
            ],
            options={
                'verbose_name': 'Dinner Platter',
                'verbose_name_plural': 'Dinner Platters',
            },
            bases=('orders.item',),
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Item')),
            ],
            bases=('orders.item',),
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Item')),
            ],
            bases=('orders.item',),
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Item')),
                ('crust', models.CharField(choices=[('Regular', 'Regular'), ('Sicilian', 'Sicilian')], max_length=30)),
                ('max_toppings', models.IntegerField(default=0)),
            ],
            bases=('orders.item',),
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Item')),
            ],
            bases=('orders.item',),
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Item')),
            ],
            bases=('orders.item',),
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Item')),
            ],
            bases=('orders.item',),
        ),
    ]
