# Generated by Django 3.0.6 on 2020-06-02 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dinnerplatters',
            options={'verbose_name': 'Dinner platters', 'verbose_name_plural': 'Dinner platters'},
        ),
        migrations.AlterModelOptions(
            name='pasta',
            options={'verbose_name': 'Pasta', 'verbose_name_plural': 'Pastas'},
        ),
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name': 'Pizza', 'verbose_name_plural': 'Pizzas'},
        ),
        migrations.AlterModelOptions(
            name='salads',
            options={'verbose_name': 'Salads', 'verbose_name_plural': 'Salads'},
        ),
        migrations.AlterModelOptions(
            name='subs',
            options={'verbose_name': 'Subs', 'verbose_name_plural': 'Subs'},
        ),
        migrations.AlterModelOptions(
            name='toppings',
            options={'verbose_name': 'Toppings', 'verbose_name_plural': 'Toppings'},
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(max_length=40)),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
