# Generated by Django 3.0.6 on 2020-06-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200602_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='toppings_1',
            field=models.CharField(blank=True, choices=[('Pepperoni', 'Pepperoni'), ('Sausage', 'Sausage'), ('Mushrooms', 'Mushrooms'), ('Onions', 'Onions'), ('Ham', 'Ham'), ('Canadian Bacon', 'Canadian Bacon'), ('Pineapple', 'Pineapple'), ('Eggplant', 'Eggplant'), ('Tomato & Basil', 'Tomato & Basil'), ('Green Peppers', 'Green Peppers'), ('Hamburger', 'Hamburger'), ('Spinach', 'Spinach'), ('Artichoke', 'Artichoke'), ('Buffalo Chicken', 'Buffalo Chicken'), ('Barbecue Chicken', 'Barbecue Chicken'), ('Anchovies', 'Anchovies'), ('Black Olives', 'Black Olives'), ('Fresh Garlic', 'Fresh Garlic'), ('Zucchini', 'Zucchini')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='toppings_2',
            field=models.CharField(blank=True, choices=[('Pepperoni', 'Pepperoni'), ('Sausage', 'Sausage'), ('Mushrooms', 'Mushrooms'), ('Onions', 'Onions'), ('Ham', 'Ham'), ('Canadian Bacon', 'Canadian Bacon'), ('Pineapple', 'Pineapple'), ('Eggplant', 'Eggplant'), ('Tomato & Basil', 'Tomato & Basil'), ('Green Peppers', 'Green Peppers'), ('Hamburger', 'Hamburger'), ('Spinach', 'Spinach'), ('Artichoke', 'Artichoke'), ('Buffalo Chicken', 'Buffalo Chicken'), ('Barbecue Chicken', 'Barbecue Chicken'), ('Anchovies', 'Anchovies'), ('Black Olives', 'Black Olives'), ('Fresh Garlic', 'Fresh Garlic'), ('Zucchini', 'Zucchini')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='toppings_3',
            field=models.CharField(blank=True, choices=[('Pepperoni', 'Pepperoni'), ('Sausage', 'Sausage'), ('Mushrooms', 'Mushrooms'), ('Onions', 'Onions'), ('Ham', 'Ham'), ('Canadian Bacon', 'Canadian Bacon'), ('Pineapple', 'Pineapple'), ('Eggplant', 'Eggplant'), ('Tomato & Basil', 'Tomato & Basil'), ('Green Peppers', 'Green Peppers'), ('Hamburger', 'Hamburger'), ('Spinach', 'Spinach'), ('Artichoke', 'Artichoke'), ('Buffalo Chicken', 'Buffalo Chicken'), ('Barbecue Chicken', 'Barbecue Chicken'), ('Anchovies', 'Anchovies'), ('Black Olives', 'Black Olives'), ('Fresh Garlic', 'Fresh Garlic'), ('Zucchini', 'Zucchini')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='toppings_4',
            field=models.CharField(blank=True, choices=[('Pepperoni', 'Pepperoni'), ('Sausage', 'Sausage'), ('Mushrooms', 'Mushrooms'), ('Onions', 'Onions'), ('Ham', 'Ham'), ('Canadian Bacon', 'Canadian Bacon'), ('Pineapple', 'Pineapple'), ('Eggplant', 'Eggplant'), ('Tomato & Basil', 'Tomato & Basil'), ('Green Peppers', 'Green Peppers'), ('Hamburger', 'Hamburger'), ('Spinach', 'Spinach'), ('Artichoke', 'Artichoke'), ('Buffalo Chicken', 'Buffalo Chicken'), ('Barbecue Chicken', 'Barbecue Chicken'), ('Anchovies', 'Anchovies'), ('Black Olives', 'Black Olives'), ('Fresh Garlic', 'Fresh Garlic'), ('Zucchini', 'Zucchini')], default=None, max_length=30),
        ),
    ]
