# Generated by Django 3.0.6 on 2020-06-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200602_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinnerplatters',
            old_name='large',
            new_name='large_price',
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
