# Generated by Django 3.0.6 on 2020-06-06 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0006_auto_20200603_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='product_type',
            field=models.CharField(choices=[('Regular Pizza', 'Regular Pizza'), ('Sicilian Pizza', 'Sicilian Pizza'), ('Toppings', 'Toppings'), ('Subs', 'Subs'), ('Pasta', 'Pasta'), ('Salads', 'Salads'), ('Dinner Platters', 'Dinner Platters')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
